/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Muru (https://sketchfab.com/muru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elf-wizard-ca5564a738174feca82c9d89610c017d
Title: Elf Wizard
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/elf_wizard.glb')
  return (
    <group {...props} dispose={null}>
      <group 
      name="5ee58d3d1c1c4921b58c16de8781249bfbx" 
      scale={[0.045, 0.045, 0.045]}
      position={[0, -1.5, 0]}>
        <group
          name="locator_staf"
          position={[11.398, 23.096, 11.84]}
          rotation={[0.304, -0.428, -0.631]}
          scale={6.367}>
          <group
            name="staf"
            position={[0.02, 0.016, -0.019]}
            rotation={[-0.175, 0.196, 1.479]}
            scale={0.157}>
            <mesh
              name="subtool215_low_mat_staf_0"
              castShadow
              receiveShadow
              geometry={nodes.subtool215_low_mat_staf_0.geometry}
              material={materials.mat_staf}
              position={[0.003, -0.165, 1.848]}
            />
          </group>
        </group>
        <group
          name="locator_book"
          position={[-22.249, 27.436, 9.753]}
          rotation={[0.118, -0.623, 2.659]}
          scale={0.797}>
          <mesh
            name="subtool202_low1_mat_book_0"
            castShadow
            receiveShadow
            geometry={nodes.subtool202_low1_mat_book_0.geometry}
            material={materials.mat_book}
            position={[0.149, 1.481, -1.778]}
            rotation={[-0.005, -0.084, 0]}
          />
        </group>
        <primitive object={nodes._rootJoint} />
        <group name="QuickRigCharacter_Reference" position={[0, 0.273, 2.94]}>
          <primitive object={nodes._rootJoint_1} />
          <skinnedMesh
            name="Object_39"
            geometry={nodes.Object_39.geometry}
            material={materials.mat_face}
            skeleton={nodes.Object_39.skeleton}
          />
          <skinnedMesh
            name="Object_41"
            geometry={nodes.Object_41.geometry}
            material={materials.mat_hat}
            skeleton={nodes.Object_41.skeleton}
          />
          <skinnedMesh
            name="Object_43"
            geometry={nodes.Object_43.geometry}
            material={materials.mat_skin}
            skeleton={nodes.Object_43.skeleton}
          />
          <skinnedMesh
            name="Object_45"
            geometry={nodes.Object_45.geometry}
            material={materials.mat_shoes}
            skeleton={nodes.Object_45.skeleton}
          />
          <skinnedMesh
            name="Object_47"
            geometry={nodes.Object_47.geometry}
            material={materials.mat_coat}
            skeleton={nodes.Object_47.skeleton}
          />
          <skinnedMesh
            name="Object_49"
            geometry={nodes.Object_49.geometry}
            material={materials.mat_shorts}
            skeleton={nodes.Object_49.skeleton}
          />
          <skinnedMesh
            name="Object_51"
            geometry={nodes.Object_51.geometry}
            material={materials.mat_shoes}
            skeleton={nodes.Object_51.skeleton}
          />
          <skinnedMesh
            name="Object_53"
            geometry={nodes.Object_53.geometry}
            material={materials.mat_shoes}
            skeleton={nodes.Object_53.skeleton}
          />
          <skinnedMesh
            name="Object_55"
            geometry={nodes.Object_55.geometry}
            material={materials.mat_shoes}
            skeleton={nodes.Object_55.skeleton}
          />
          <skinnedMesh
            name="Object_57"
            geometry={nodes.Object_57.geometry}
            material={materials.mat_coat}
            skeleton={nodes.Object_57.skeleton}
          />
          <skinnedMesh
            name="Object_59"
            geometry={nodes.Object_59.geometry}
            material={materials.mat_shoes}
            skeleton={nodes.Object_59.skeleton}
          />
          <skinnedMesh
            name="Object_61"
            geometry={nodes.Object_61.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_61.skeleton}
          />
          <skinnedMesh
            name="Object_63"
            geometry={nodes.Object_63.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_63.skeleton}
          />
          <skinnedMesh
            name="Object_65"
            geometry={nodes.Object_65.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_65.skeleton}
          />
          <skinnedMesh
            name="Object_67"
            geometry={nodes.Object_67.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_67.skeleton}
          />
          <skinnedMesh
            name="Object_69"
            geometry={nodes.Object_69.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_69.skeleton}
          />
          <skinnedMesh
            name="Object_71"
            geometry={nodes.Object_71.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_71.skeleton}
          />
          <skinnedMesh
            name="Object_73"
            geometry={nodes.Object_73.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_73.skeleton}
          />
          <skinnedMesh
            name="Object_75"
            geometry={nodes.Object_75.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_75.skeleton}
          />
          <skinnedMesh
            name="Object_77"
            geometry={nodes.Object_77.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_77.skeleton}
          />
          <skinnedMesh
            name="Object_79"
            geometry={nodes.Object_79.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_79.skeleton}
          />
          <skinnedMesh
            name="Object_81"
            geometry={nodes.Object_81.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_81.skeleton}
          />
          <skinnedMesh
            name="Object_83"
            geometry={nodes.Object_83.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_83.skeleton}
          />
          <skinnedMesh
            name="Object_85"
            geometry={nodes.Object_85.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_85.skeleton}
          />
          <skinnedMesh
            name="Object_87"
            geometry={nodes.Object_87.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_87.skeleton}
          />
          <skinnedMesh
            name="Object_89"
            geometry={nodes.Object_89.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_89.skeleton}
          />
          <skinnedMesh
            name="Object_91"
            geometry={nodes.Object_91.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_91.skeleton}
          />
          <skinnedMesh
            name="Object_93"
            geometry={nodes.Object_93.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_93.skeleton}
          />
          <skinnedMesh
            name="Object_95"
            geometry={nodes.Object_95.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_95.skeleton}
          />
          <skinnedMesh
            name="Object_97"
            geometry={nodes.Object_97.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_97.skeleton}
          />
          <skinnedMesh
            name="Object_99"
            geometry={nodes.Object_99.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_99.skeleton}
          />
          <skinnedMesh
            name="Object_101"
            geometry={nodes.Object_101.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_101.skeleton}
          />
          <skinnedMesh
            name="Object_103"
            geometry={nodes.Object_103.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_103.skeleton}
          />
          <skinnedMesh
            name="Object_105"
            geometry={nodes.Object_105.geometry}
            material={materials.mat_hair}
            skeleton={nodes.Object_105.skeleton}
          />
          <skinnedMesh
            name="Object_107"
            geometry={nodes.Object_107.geometry}
            material={materials.lambert1}
            skeleton={nodes.Object_107.skeleton}
          />
        </group>
        <mesh
          name="polySurface3_lambert1_0"
          castShadow
          receiveShadow
          geometry={nodes.polySurface3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          name="polySurface4_lambert1_0"
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/elf_wizard.glb')
